# The following redirect is intended for use with most SPAs that handle
# routing internally.
# https://www.netlify.com/docs/netlify-toml-reference/
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
